name: workflow Test

on:
  push:
    branches: 
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a working-directory
        run: echo "Welcome to our first GITHUB WorkFlow"
        
      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: list repository
        run: ls -l
      

        
        
    
