name: just test manual github action

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: " Choose environment"
        required: true
        default: staging
        type: choice
        options:
          - Deployment
          - staging
          - production
jobs:
  manual-job:
    runs-on: ubuntu-slim
    steps:
      - name: Deploy application
        run: echo "sent new appliction to production environment"
  
