name: Handle Incident Report

on:
  repository_dispatch:
    types: [incident_report]

jobs:
  handle_incident:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Sami step
        run: echo "Sami handling incident report"
      
      - name: Print incident
        run: echo "Incident report received"


# curl --ssl-no-revoke -X POST \
#   -H "Authorization: token $GITHUB_PAT" \
#   -H "Accept: application/vnd.github.v3+json" \
#   https://api.github.com/repos/Basil-AUTO/github-ActionWorkflow/dispatches \
#   -d '{"event_type":"incident_report"}'
