on:
  push:
    branches:
      - main
      - "realese/**"

    paths:
      - "src/**"
      #- ".github/workflows/**" # Runs if workflow files change
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: Run tests
        run: npm test
